---
settings:
  react:
    version: detect
env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'prettier'
rules:
  "no-use-before-define": "off"
  "@typescript-eslint/no-use-before-define":
    - "error"
