# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 04-06-2017
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: parham-cv parham-cv-fa

parham-cv:
	cd english && $(MAKE)
parham-cv-fa:
	cd farsi && $(MAKE)
