# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 15-01-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: parham-cv

parham-cv: friggeri-cv.cls parham-cv.sty parham-cv.tex
	xelatex parham-cv.tex
parham-cv-fa: friggeri-cv-fa.cls parham-cv.sty parham-cv-fa.tex
	xelatex parham-cv-fa.tex
